### ISSUE TITLE
Use bindActionCreators for creating mapDispatchToProps

### ISSUE THREAD

**Issue by orlov-vo** [Askadar/pomodori#1]
For example: https://github.com/Askadar/pomodori/blob/7e27d7c3d6c5a521243574dd2757196e3238288b/src/view/App.js#L101

In this case you can use `bindActionCreators` - it is easy for writing and reading ;)
https://redux.js.org/api-reference/bindactioncreators

**Comment by Askadar** [comment]
Oh, thanks for proposal. I'll check it out when I get some time.

**Comment by Askadar** [comment]
Hi again, I've checked `bindActionCreators` function and will deny its use for now, since I'm using react-redux, which already does basically same thing wrapping plaing object with functions into dispatchable set. It's just I forgot to use simple object instead of function wrapping dispatch around actions, which is usually used together with redux-thunk to create asynchronous action dispatching.

But I've done some refactor and cleaned up code style to more uniform and clear (in my understanding) writing, like refactored TimeContols (previously inlined into App.js with everything else):

https://github.com/Askadar/pomodori/blob/f68efad0b6e6b25a107c45aa7144f444c7f5bab8/src/view/Pomo/TimeControls.jsx#L7

If there are no technical benefits of switching to `bindActionCreators`, except server-rendering which is out of question for now or code readability which should be solved, I'll leave everyhting else as is and close this issue.
